version: 0.2

phases:
  build:
    commands:
      - echo Kwon Pg build...
      - chmod +x ./KWON_PG/gradlew
      - ./KWON_PG/gradlew build
  post_build:
    commands:
      - echo $(basename ./KWON_PG/build/libs/*.jar)
      - pwd
artifacts:
  files:
    - ./KWON_PG/appspec.yml
    - build/libs/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'