version: 0.2

phases:
  build:
    commands:
      - echo Kwon Pg build...
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.war)
      - pwd
artifacts:
  files:
    - ./appspec.yml
    - build/libs/*.war
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'